% The code below for matlab was made by Roman and has been customised
% as per the needs of the Neuroscience Dept-NYSPI.
% Date: 09/12/2002
% ===============================================================================
% This routine uses the info from the 'hdr' array structure generated by the routine
% 'hdr=read_headerfile(filename)' to read the '.img' file and outputs the entire 
% 3D intensity-valued matrix
function Inty_val_mat=read_imagefile(filename,hdr)

% fid=fopen(filename,'r','n'); %opens img file
fid=fopen(filename,'r',hdr.machineformat); %opens img file
% 'native' or 'n':	the numeric format of the machine you are currently running
% for other machine formats check the matlab help document on 'fopen'

% now set precision depending on value of bitpix in hdr file
switch hdr.bitpix
        case 8		
            precision='int8';
        case 16
            precision='int16';
        case 32
            precision='float32';   
        otherwise
            error('BRAINFIT:insufficientData',...
                 ['Unable to handle given bits/pixel value: ',hdr.bitpix]);   
end 

xdim=hdr.dim(2);
ydim=hdr.dim(3);
n_slices=hdr.dim(4);
temp=fread(fid,xdim*ydim*n_slices,precision);

if hdr.scale_factor==0; hdr.scale_factor=1; else end
Inty_val_mat=hdr.scale_factor*reshape(temp,xdim,ydim,n_slices);

fclose(fid); % closes file incl. messages